export const templates = [
  {
    id: "mosque-gold",
    name: "Golden Mosque",
    description: "Elegant mosque silhouette with golden accents",
    gradient: "linear-gradient(135deg, #0a1628 0%, #1a2744 40%, #0d1f3c 100%)",
    accentColor: "#d4af37",
    textColor: "#f5e6c8",
    decorationType: "mosque",
    borderStyle: "2px solid rgba(212, 175, 55, 0.4)",
  },
  {
    id: "crescent-night",
    name: "Crescent Moon",
    description: "Beautiful crescent moon under starry sky",
    gradient: "linear-gradient(180deg, #0b0e2d 0%, #1b1e4b 50%, #2d1b69 100%)",
    accentColor: "#e8d48b",
    textColor: "#e8e0f0",
    decorationType: "crescent",
    borderStyle: "2px solid rgba(232, 212, 139, 0.3)",
  },
  {
    id: "lantern-glow",
    name: "Lantern Glow",
    description: "Warm glowing lanterns with festive feel",
    gradient: "linear-gradient(135deg, #1a0a2e 0%, #2d1654 40%, #4a1942 100%)",
    accentColor: "#ff9f43",
    textColor: "#ffecd2",
    decorationType: "lantern",
    borderStyle: "2px solid rgba(255, 159, 67, 0.3)",
  },
  {
    id: "geometric-emerald",
    name: "Islamic Geometry",
    description: "Intricate geometric patterns in emerald & gold",
    gradient: "linear-gradient(135deg, #0a2e1a 0%, #0d3b2a 40%, #1a4d3a 100%)",
    accentColor: "#50c878",
    textColor: "#d4f0e0",
    decorationType: "geometric",
    borderStyle: "2px solid rgba(80, 200, 120, 0.3)",
  },
  {
    id: "floral-rose",
    name: "Floral Arabesque",
    description: "Delicate floral patterns with rose tones",
    gradient: "linear-gradient(135deg, #2d1329 0%, #4a1942 40%, #3d1535 100%)",
    accentColor: "#e896b8",
    textColor: "#fce4ec",
    decorationType: "floral",
    borderStyle: "2px solid rgba(232, 150, 184, 0.3)",
  },
  {
    id: "royal-blue",
    name: "Royal Night",
    description: "Majestic royal blue with silver stars",
    gradient: "linear-gradient(135deg, #0a1929 0%, #132f4c 40%, #0d47a1 100%)",
    accentColor: "#90caf9",
    textColor: "#e3f2fd",
    decorationType: "stars",
    borderStyle: "2px solid rgba(144, 202, 249, 0.3)",
  },
  // --- Additional Templates ---
  {
    id: "sunset-dunes",
    name: "Sunset Dunes",
    description: "Golden desert sunset with warm gradient",
    gradient: "linear-gradient(180deg, #1a0a00 0%, #4a2010 30%, #8b4513 60%, #d4873a 100%)",
    accentColor: "#f4c778",
    textColor: "#ffecd2",
    decorationType: "crescent",
    borderStyle: "2px solid rgba(244, 199, 120, 0.3)",
  },
  {
    id: "midnight-teal",
    name: "Midnight Teal",
    description: "Deep teal with shimmering silver accents",
    gradient: "linear-gradient(135deg, #041c1c 0%, #0a3535 40%, #0e4d4d 100%)",
    accentColor: "#7dd8c7",
    textColor: "#d0f0ea",
    decorationType: "geometric",
    borderStyle: "2px solid rgba(125, 216, 199, 0.3)",
  },
  {
    id: "burgundy-silk",
    name: "Burgundy Silk",
    description: "Rich burgundy with elegant gold details",
    gradient: "linear-gradient(135deg, #2a0a14 0%, #4d1525 40%, #6b1d34 100%)",
    accentColor: "#e8b84d",
    textColor: "#f5e0d0",
    decorationType: "floral",
    borderStyle: "2px solid rgba(232, 184, 77, 0.3)",
  },
  {
    id: "aurora-purple",
    name: "Aurora Glow",
    description: "Mystical purple aurora with soft lights",
    gradient: "linear-gradient(135deg, #1a0533 0%, #2d1264 40%, #4a1fa0 70%, #2d1264 100%)",
    accentColor: "#c490f5",
    textColor: "#e8d8f8",
    decorationType: "stars",
    borderStyle: "2px solid rgba(196, 144, 245, 0.3)",
  },
  {
    id: "olive-garden",
    name: "Olive Garden",
    description: "Natural olive tones with earthy warmth",
    gradient: "linear-gradient(135deg, #1a1c0a 0%, #2e3315 40%, #4a5520 100%)",
    accentColor: "#c8d96f",
    textColor: "#e8ecd0",
    decorationType: "lantern",
    borderStyle: "2px solid rgba(200, 217, 111, 0.3)",
  },
  {
    id: "ocean-pearl",
    name: "Ocean Pearl",
    description: "Deep ocean blue with pearly white glow",
    gradient: "linear-gradient(180deg, #050d1a 0%, #0c1e3a 40%, #1a3a6a 100%)",
    accentColor: "#a8d4e6",
    textColor: "#d8eef8",
    decorationType: "mosque",
    borderStyle: "2px solid rgba(168, 212, 230, 0.3)",
  },
];

export const cardFonts = [
  {
    id: "playfair",
    name: "Playfair Display",
    cssVar: "var(--font-playfair)",
    preview: "Elegant Serif",
    category: "Serif",
  },
  {
    id: "dancing",
    name: "Dancing Script",
    cssVar: "var(--font-dancing)",
    preview: "Handwritten",
    category: "Script",
  },
  {
    id: "lora",
    name: "Lora",
    cssVar: "var(--font-lora)",
    preview: "Classic Serif",
    category: "Serif",
  },
  {
    id: "amiri",
    name: "Amiri",
    cssVar: "var(--font-amiri)",
    preview: "Arabic Style",
    category: "Serif",
  },
  {
    id: "greatvibes",
    name: "Great Vibes",
    cssVar: "var(--font-greatvibes)",
    preview: "Calligraphy",
    category: "Script",
  },
  {
    id: "cormorant",
    name: "Cormorant Garamond",
    cssVar: "var(--font-cormorant)",
    preview: "Refined Serif",
    category: "Serif",
  },
  {
    id: "merriweather",
    name: "Merriweather",
    cssVar: "var(--font-merriweather)",
    preview: "Warm Serif",
    category: "Serif",
  },
  {
    id: "caveat",
    name: "Caveat",
    cssVar: "var(--font-caveat)",
    preview: "Casual Hand",
    category: "Handwriting",
  },
];

export function getTemplateById(id) {
  return templates.find((t) => t.id === id) || templates[0];
}

export function getFontById(id) {
  return cardFonts.find((f) => f.id === id) || cardFonts[0];
}
